name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # CI job to test and build the application
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build the application
        run: npm run build

  # CD job to deploy the application
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no user@yourserver.com "cd /path/to/app && git pull && npm install && pm2 restart app"
        
      - name: Notify Slack of Deployment Success
        uses: slackapi/slack-github-action@v1.21.0
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          channel-id: 'your-channel-id'
          text: 'Deployment was successful!'

